name: Build

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: manifest

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: manifest
          toolchains: arm-zephyr-eabi

      - name: Build
        working-directory: manifest
        run: |
          west build -b nice_nano_v2 app -- -DOVERLAY_CONFIG="usb.conf"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        working-directory: manifest
        with:
          name: build-artifacts
          path: |
            build/zephyr/zephyr.elf
            build/zephyr/zephyr.uf2
            build/zephyr/.config

      - name: Rename files for export
        working-directory: manifest
        run: |
          mv build/zephyr/zephyr.uf2 ../mixy_beta_A.uf2

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mixy_beta_A.uf2
