name: Build

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: app

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -b nice_nano_v2 app -- -DOVERLAY_CONFIG="usb.conf"