name: Build in container
on:
  push:
    branches:
      - "**"

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hw_rev: ["A", "B", "C"]
    
    container: 
      image: ghcr.io/mixylabs/ci:main
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: manifest

      - name: Do smth with hw_rev
        run: |
          echo "Building for hardware revision ${{ matrix.hw_rev }}"

      - name: Initialize west
        working-directory: manifest
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build
        working-directory: manifest
        run: |
          west build -b nice_nano_v2 app -- -DOVERLAY_CONFIG="usb.conf"